import os

import pytest

from praxis.model import OutputFile
from praxis.sync import (
    BEGIN,
    END,
    NOTICE,
    SyncError,
    apply,
    managed_block,
    merge,
    plan,
    plan_stale,
    unmerge,
)


def test_merge_into_missing_file_creates_block():
    assert merge(None, "Rules.") == managed_block("Rules.") + "\n"


def test_merge_appends_block_after_existing_content():
    result = merge("# My project\n\nHand-written notes.\n", "Rules.")

    assert result == "# My project\n\nHand-written notes.\n\n" + managed_block("Rules.") + "\n"


def test_merge_replaces_only_the_managed_block():
    existing = f"Before.\n\n{BEGIN}\nold\n{END}\n\nAfter.\n"

    result = merge(existing, "new")

    assert result == f"Before.\n\n{managed_block('new')}\n\nAfter.\n"


def test_merge_is_idempotent():
    once = merge("Intro.\n", "Rules.")

    assert merge(once, "Rules.") == once


@pytest.mark.parametrize(
    "existing",
    [
        f"{BEGIN}\nno end\n",
        f"no begin\n{END}\n",
        f"{END}\n{BEGIN}\n",
        f"{BEGIN}\n{END}\n{BEGIN}\n{END}\n",
    ],
)
def test_merge_rejects_malformed_markers(existing):
    with pytest.raises(SyncError, match="malformed praxis markers"):
        merge(existing, "Rules.")


def test_plan_and_apply_write_only_changed_files(tmp_path):
    (tmp_path / "CLAUDE.md").write_text(merge(None, "@AGENTS.md"), encoding="utf-8")
    outputs = (OutputFile("AGENTS.md", "Rules."), OutputFile("CLAUDE.md", "@AGENTS.md"))

    changes = plan(tmp_path, outputs)
    written = apply(changes)

    assert [change.relpath for change in changes if change.changed] == ["AGENTS.md"]
    assert written == (tmp_path / "AGENTS.md",)
    assert all(not change.changed for change in plan(tmp_path, outputs))


def test_apply_creates_parent_directories(tmp_path):
    apply(plan(tmp_path, (OutputFile(".github/copilot-instructions.md", "Rules."),)))

    assert (tmp_path / ".github" / "copilot-instructions.md").is_file()


def test_plan_reports_path_of_malformed_file(tmp_path):
    (tmp_path / "AGENTS.md").write_text(f"{BEGIN}\n", encoding="utf-8")

    with pytest.raises(SyncError, match="AGENTS.md"):
        plan(tmp_path, (OutputFile("AGENTS.md", "Rules."),))


def test_plan_preserves_crlf_line_endings(tmp_path):
    path = tmp_path / "AGENTS.md"
    path.write_bytes(b"# Title\r\n\r\nNotes.\r\n")
    outputs = (OutputFile("AGENTS.md", "Rule one.\n\nRule two."),)

    apply(plan(tmp_path, outputs))

    raw = path.read_bytes()
    assert raw.startswith(b"# Title\r\n\r\nNotes.\r\n\r\n")
    assert b"\n" not in raw.replace(b"\r\n", b"")
    assert all(not change.changed for change in plan(tmp_path, outputs))


def test_apply_preserves_file_mode_and_leaves_no_temp_files(tmp_path):
    path = tmp_path / "AGENTS.md"
    path.write_text("Notes.\n", encoding="utf-8")
    path.chmod(0o640)

    apply(plan(tmp_path, (OutputFile("AGENTS.md", "Rules."),)))

    assert path.stat().st_mode & 0o777 == 0o640
    assert sorted(p.name for p in tmp_path.iterdir()) == ["AGENTS.md"]


def test_apply_writes_through_symlinks(tmp_path):
    real = tmp_path / "shared.md"
    real.write_text("Notes.\n", encoding="utf-8")
    (tmp_path / "AGENTS.md").symlink_to(real)

    apply(plan(tmp_path, (OutputFile("AGENTS.md", "Rules."),)))

    assert (tmp_path / "AGENTS.md").is_symlink()
    assert "Rules." in real.read_text(encoding="utf-8")


def test_owned_file_is_written_verbatim(tmp_path):
    content = "---\nname: x\n---\n\n" + NOTICE + "\n\nBody.\n"

    apply(plan(tmp_path, (OutputFile(".agents/skills/x/SKILL.md", content, managed=False),)))

    assert (tmp_path / ".agents/skills/x/SKILL.md").read_text(encoding="utf-8") == content


def test_owned_file_previously_generated_is_replaced(tmp_path):
    path = tmp_path / "SKILL.md"
    path.write_text(f"{NOTICE}\nold\n", encoding="utf-8")

    (change,) = plan(tmp_path, (OutputFile("SKILL.md", f"{NOTICE}\nnew\n", managed=False),))

    assert change.changed
    assert change.content == f"{NOTICE}\nnew\n"


def test_owned_file_refuses_to_overwrite_user_file(tmp_path):
    (tmp_path / "SKILL.md").write_text("My own skill.\n", encoding="utf-8")

    with pytest.raises(SyncError, match="was not generated by praxis"):
        plan(tmp_path, (OutputFile("SKILL.md", f"{NOTICE}\nnew\n", managed=False),))


def test_owned_file_refuses_dangling_symlink(tmp_path):
    (tmp_path / "SKILL.md").symlink_to(tmp_path / "outside" / "target.md")

    with pytest.raises(SyncError, match="dangling symlink"):
        plan(tmp_path, (OutputFile("SKILL.md", f"{NOTICE}\nnew\n", managed=False),))


def test_unmerge_removes_block_and_keeps_user_content():
    existing = merge("# Notes\n\nMine.\n", "Rules.")

    assert unmerge(existing) == "# Notes\n\nMine.\n"


def test_unmerge_returns_none_when_only_the_block_remains():
    assert unmerge(merge(None, "Rules.")) is None


def test_unmerge_leaves_files_without_markers_alone():
    assert unmerge("# Notes\n") == "# Notes\n"


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def test_plan_stale_deletes_owned_files_no_longer_generated(tmp_path):
    kept = write(tmp_path / ".agents/skills/keep/SKILL.md", f"{NOTICE}\nkeep\n")
    stale = write(tmp_path / ".agents/skills/gone/references/a.md", f"{NOTICE}\nold\n")
    users = write(tmp_path / ".agents/skills/mine/SKILL.md", "My own skill.\n")

    changes = plan_stale(
        tmp_path,
        outputs=(OutputFile(".agents/skills/keep/SKILL.md", "x", managed=False),),
        owned_dirs=(".agents/skills", ".cursor/rules"),
        managed_paths=(),
    )

    assert [(change.relpath, change.deleted) for change in changes] == [
        (".agents/skills/gone/references/a.md", True)
    ]
    apply(changes)
    assert not stale.exists() and not (tmp_path / ".agents/skills/gone").exists()
    assert kept.exists() and users.exists()
    assert (tmp_path / ".agents/skills").is_dir()


def test_plan_stale_skips_symlinks(tmp_path):
    target = write(tmp_path / "elsewhere.md", f"{NOTICE}\n")
    link = tmp_path / ".cursor/rules/link.mdc"
    link.parent.mkdir(parents=True)
    link.symlink_to(target)

    assert plan_stale(tmp_path, (), (".cursor/rules",), ()) == ()


def test_plan_stale_removes_block_from_managed_file_no_longer_generated(tmp_path):
    only_block = write(tmp_path / ".github/copilot-instructions.md", merge(None, "Rules."))
    with_notes = write(tmp_path / "NOTES.md", merge("Mine.\n", "Rules."))
    untouched = write(tmp_path / "PLAIN.md", "No markers.\n")

    changes = plan_stale(
        tmp_path, (), (), (".github/copilot-instructions.md", "NOTES.md", "PLAIN.md", "MISSING.md")
    )
    apply(changes)

    assert not only_block.exists()
    assert with_notes.read_text(encoding="utf-8") == "Mine.\n"
    assert untouched.read_text(encoding="utf-8") == "No markers.\n"


def test_plan_stale_ignores_managed_paths_that_are_still_generated(tmp_path):
    write(tmp_path / "AGENTS.md", merge(None, "Rules."))

    assert plan_stale(tmp_path, (OutputFile("AGENTS.md", "Rules."),), (), ("AGENTS.md",)) == ()


def test_plan_stale_ignores_owned_dir_symlinked_outside_root(tmp_path):
    outside = write(tmp_path / "outside" / "skills" / "x" / "SKILL.md", f"{NOTICE}\n")
    project = tmp_path / "project"
    (project / ".claude").mkdir(parents=True)
    (project / ".claude" / "skills").symlink_to(tmp_path / "outside" / "skills")

    assert plan_stale(project, (), (".claude/skills",), ()) == ()
    assert outside.exists()


def test_plan_stale_requires_notice_as_its_own_line_near_the_top(tmp_path):
    write(tmp_path / ".cursor/rules/quoted.mdc", f"Our docs quote it: {NOTICE}\n")
    write(tmp_path / ".cursor/rules/late.mdc", "line\n" * 50 + f"{NOTICE}\n")

    assert plan_stale(tmp_path, (), (".cursor/rules",), ()) == ()


def test_plan_stale_keeps_a_file_that_is_also_a_produced_path(tmp_path):
    produced = write(tmp_path / ".agents/skills/Foo/SKILL.md", f"{NOTICE}\n")
    alias = tmp_path / ".agents/skills/alias/SKILL.md"
    alias.parent.mkdir()
    # A hard link is the same file under another spelling, as with case-insensitive filesystems.
    os.link(produced, alias)

    outputs = (OutputFile(".agents/skills/Foo/SKILL.md", NOTICE, managed=False),)

    assert plan_stale(tmp_path, outputs, (".agents/skills",), ()) == ()


def test_apply_refuses_to_delete_a_file_changed_since_planning(tmp_path):
    path = write(tmp_path / ".cursor/rules/old.mdc", f"{NOTICE}\nold\n")
    changes = plan_stale(tmp_path, (), (".cursor/rules",), ())
    path.write_text(f"{NOTICE}\nedited by hand\n", encoding="utf-8")

    with pytest.raises(SyncError, match="changed since"):
        apply(changes)
    assert path.exists()


def test_apply_tolerates_a_stale_file_already_deleted(tmp_path):
    path = write(tmp_path / ".cursor/rules/old.mdc", f"{NOTICE}\n")
    changes = plan_stale(tmp_path, (), (".cursor/rules",), ())
    path.unlink()

    assert apply(changes) == ()


def test_plan_stale_leaves_symlinked_managed_files_alone(tmp_path):
    agents = write(tmp_path / "AGENTS.md", merge(None, "Rules."))
    (tmp_path / "CLAUDE.md").symlink_to(agents)

    assert plan_stale(tmp_path, (), (), ("CLAUDE.md",)) == ()
