import pytest

from praxis import adapters
from praxis.adapters import Adapter, available_targets, get_adapter, register_adapter
from praxis.cli import main
from praxis.init import STARTER_RULES
from praxis.rules import parse, parse_file
from praxis.sync import parse_targets, sync

RULES = """\
---
name: acme
---

# Acme standards

Rules for every agent.

- Be kind to reviewers.

## Testing

Tests keep us honest.

- Write a test for every bug fix.
  - Start with a failing test.
- Keep unit tests fast.

### Fixtures

- Prefer factories over shared fixtures.

## Style

```python
x = 1  # not a rule
```
"""


@pytest.fixture
def ruleset():
    return parse(RULES)


@pytest.fixture
def rules_file(tmp_path):
    path = tmp_path / "PRAXIS.md"
    path.write_text(RULES)
    return path


def test_builtin_targets_registered():
    assert {"claude", "codex"} <= set(available_targets())
    assert get_adapter("claude").filename == "CLAUDE.md"
    assert get_adapter("codex").filename == "AGENTS.md"


def test_unknown_target_lists_available():
    with pytest.raises(ValueError, match="Unknown target 'cursor'.*claude"):
        get_adapter("cursor")


@pytest.mark.parametrize(
    "value, expected",
    [
        ("claude,codex", ["claude", "codex"]),
        (" Claude , codex,claude ", ["claude", "codex"]),
        (["claude", "codex"], ["claude", "codex"]),
        (["codex,claude"], ["codex", "claude"]),
    ],
)
def test_parse_targets(value, expected):
    assert parse_targets(value) == expected


def test_parse_targets_rejects_empty_and_unknown():
    with pytest.raises(ValueError, match="No sync targets"):
        parse_targets(" , ")
    with pytest.raises(ValueError, match="Unknown target"):
        parse_targets("claude,nope")


def test_render_markdown(ruleset):
    assert get_adapter("claude").render(ruleset) == """\
<!-- Generated by praxis-agents. Do not edit by hand: change the rules file and run `praxis sync`. -->

# Acme standards

Follow these project rules when working in this repository.

Rules for every agent.

- Be kind to reviewers.

## Testing

Tests keep us honest.

- Write a test for every bug fix.
  - Start with a failing test.
- Keep unit tests fast.

### Fixtures

- Prefer factories over shared fixtures.

## Style

```python
x = 1  # not a rule
```
"""


def test_codex_renders_same_rules(ruleset):
    claude = get_adapter("claude").render(ruleset)
    codex = get_adapter("codex").render(ruleset)
    assert codex == claude


def test_render_untitled_empty_ruleset():
    text = get_adapter("codex").render(parse(""))
    assert "# Project rules\n" in text


def test_render_names_source_file(rules_file):
    text = get_adapter("claude").render(parse_file(rules_file))
    assert text.startswith("<!-- Generated by praxis-agents from PRAXIS.md.")


def test_starter_rules_round_trip(tmp_path):
    sync(parse(STARTER_RULES), "claude", tmp_path)
    text = (tmp_path / "CLAUDE.md").read_text()
    for rule in parse(STARTER_RULES).all_rules():
        assert f"- {rule.text}" in text


def test_sync_writes_both_files(tmp_path, ruleset):
    results = sync(ruleset, "claude,codex", tmp_path)

    assert [(r.target, r.path.name, r.changed) for r in results] == [
        ("claude", "CLAUDE.md", True),
        ("codex", "AGENTS.md", True),
    ]
    for name in ("CLAUDE.md", "AGENTS.md"):
        assert "- Write a test for every bug fix." in (tmp_path / name).read_text()


def test_sync_is_idempotent(tmp_path, ruleset):
    sync(ruleset, "claude", tmp_path)
    mtime = (tmp_path / "CLAUDE.md").stat().st_mtime_ns

    results = sync(ruleset, "claude", tmp_path)

    assert results[0].changed is False
    assert (tmp_path / "CLAUDE.md").stat().st_mtime_ns == mtime


def test_sync_overwrites_stale_file(tmp_path, ruleset):
    (tmp_path / "AGENTS.md").write_text("old\n")
    [result] = sync(ruleset, "codex", tmp_path)
    assert result.changed is True
    assert "## Testing" in (tmp_path / "AGENTS.md").read_text()


def test_sync_dry_run_writes_nothing(tmp_path, ruleset):
    results = sync(ruleset, "claude,codex", tmp_path, dry_run=True)
    assert all(r.changed for r in results)
    assert list(tmp_path.iterdir()) == []


def test_sync_only_selected_target(tmp_path, ruleset):
    sync(ruleset, "codex", tmp_path)
    assert (tmp_path / "AGENTS.md").exists()
    assert not (tmp_path / "CLAUDE.md").exists()


def test_sync_creates_output_dir(tmp_path, ruleset):
    sync(ruleset, "claude", tmp_path / "out" / "nested")
    assert (tmp_path / "out" / "nested" / "CLAUDE.md").exists()


def test_custom_adapter_plugs_in(tmp_path, ruleset):
    class CursorAdapter(Adapter):
        name = "test-cursor"
        filename = ".cursorrules"

        def render(self, rs):
            return "".join(f"{rule.id}\n" for rule in rs.all_rules())

    register_adapter(CursorAdapter)
    try:
        sync(ruleset, "test-cursor", tmp_path)
        assert (tmp_path / ".cursorrules").read_text().splitlines() == [
            "be-kind-to-reviewers",
            "testing/write-a-test-for-every-bug-fix",
            "testing/keep-unit-tests-fast",
            "fixtures/prefer-factories-over-shared-fixtures",
        ]
    finally:
        adapters._REGISTRY.pop("test-cursor")


def test_cli_sync_targets(rules_file, capsys):
    assert main(["sync", str(rules_file), "--target", "claude,codex"]) == 0

    out = capsys.readouterr().out
    assert "Wrote" in out and "CLAUDE.md (claude)" in out and "AGENTS.md (codex)" in out
    assert (rules_file.parent / "CLAUDE.md").exists()
    assert (rules_file.parent / "AGENTS.md").exists()

    assert main(["sync", str(rules_file), "-t", "claude"]) == 0
    assert "Up to date" in capsys.readouterr().out


def test_cli_sync_defaults_to_all_targets_and_cwd_rules(rules_file, monkeypatch):
    monkeypatch.chdir(rules_file.parent)
    assert main(["sync"]) == 0
    for target in available_targets():
        assert (rules_file.parent / get_adapter(target).filename).exists()


def test_cli_sync_output_dir_and_dry_run(rules_file, tmp_path, capsys):
    out_dir = tmp_path / "out"
    assert main(["sync", str(rules_file), "-o", str(out_dir), "--dry-run"]) == 0
    assert "Would write" in capsys.readouterr().out
    assert not out_dir.exists()

    assert main(["sync", str(rules_file), "-o", str(out_dir)]) == 0
    assert (out_dir / "CLAUDE.md").exists()


def test_cli_sync_unknown_target(rules_file, capsys):
    assert main(["sync", str(rules_file), "--target", "nope"]) == 1
    assert "Unknown target 'nope'" in capsys.readouterr().err


def test_cli_sync_missing_rules_file(tmp_path, capsys):
    assert main(["sync", str(tmp_path / "missing.md")]) == 1
    assert "run `praxis init`" in capsys.readouterr().err


def test_cli_sync_bad_rules_file(tmp_path, capsys):
    bad = tmp_path / "PRAXIS.md"
    bad.write_text("```\nunterminated\n")
    assert main(["sync", str(bad)]) == 1
    assert "unterminated code fence" in capsys.readouterr().err
