"""Core data model: a pack of rules and skills, and the files adapters render from it."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

Scope = Literal["always", "glob"]
SCOPES: tuple[Scope, ...] = ("always", "glob")

BEGIN_MARKER = "<!-- praxis:begin -->"
END_MARKER = "<!-- praxis:end -->"
NOTICE = "<!-- Generated by praxis. Edit the praxis source files, then run `praxis sync`. -->"


@dataclass(frozen=True)
class ForbidCheck:
    """Fail if a line added by the change matches ``pattern`` (a Python regex)."""

    pattern: str
    message: str = ""


@dataclass(frozen=True)
class RunCheck:
    """Fail if ``command`` (argv, run without a shell) exits non-zero."""

    command: tuple[str, ...]
    message: str = ""


Check = ForbidCheck | RunCheck


@dataclass(frozen=True)
class Rule:
    """One instruction an agent should follow, plus optional checks for ``praxis verify``."""

    id: str
    body: str
    scope: Scope = "always"
    globs: tuple[str, ...] = ()
    checks: tuple[Check, ...] = ()
    judge: bool = True  # False for rules a diff can't show, such as process or planning rules


@dataclass(frozen=True)
class Reference:
    """A supporting file a skill reads on demand."""

    path: str  # POSIX path relative to the skill directory, e.g. "references/metrics.md"
    content: str


@dataclass(frozen=True)
class Skill:
    """An on-demand capability in the Agent Skills format (``SKILL.md`` + references)."""

    name: str
    description: str
    body: str
    references: tuple[Reference, ...] = ()


@dataclass(frozen=True)
class Pack:
    """Everything loaded from a praxis source directory."""

    rules: tuple[Rule, ...] = ()
    skills: tuple[Skill, ...] = ()


@dataclass(frozen=True)
class OutputFile:
    """One generated file.

    ``managed`` files get ``content`` inside praxis markers, keeping the rest of the file.
    Otherwise praxis owns the whole file, and ``content`` must include :data:`NOTICE`.
    """

    path: str  # POSIX path relative to the project root
    content: str
    managed: bool = True
