"""Write rendered output into files, touching only the praxis-managed block."""

from __future__ import annotations

import os
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from praxis.model import BEGIN_MARKER as BEGIN
from praxis.model import END_MARKER as END
from praxis.model import NOTICE, OutputFile

DEFAULT_FILE_MODE = 0o644


class SyncError(ValueError):
    """Raised when an existing file can't be merged safely."""


@dataclass(frozen=True)
class FileChange:
    """The planned new content for one file."""

    relpath: str
    path: Path
    content: str
    changed: bool


def managed_block(content: str) -> str:
    body = content.strip()
    inner = f"{NOTICE}\n{body}\n" if body else f"{NOTICE}\n"
    return f"{BEGIN}\n{inner}{END}"


def merge(existing: str | None, content: str) -> str:
    """Return ``existing`` with its managed block replaced (or appended) by ``content``."""
    block = managed_block(content)
    if existing is None or not existing.strip():
        return block + "\n"

    begins, ends = existing.count(BEGIN), existing.count(END)
    if begins == 0 and ends == 0:
        return existing.rstrip("\n") + "\n\n" + block + "\n"
    if begins != 1 or ends != 1 or existing.index(BEGIN) > existing.index(END):
        raise SyncError(f"malformed praxis markers; expected one {BEGIN} followed by one {END}")

    start = existing.index(BEGIN)
    stop = existing.index(END) + len(END)
    return existing[:start] + block + existing[stop:]


def own(existing: str | None, content: str) -> str:
    """Return ``content`` for a praxis-owned file, refusing to replace a file praxis didn't write."""
    if existing is not None and NOTICE not in existing:
        raise SyncError("file exists and was not generated by praxis; move or delete it first")
    return content


def plan(root: Path, outputs: Iterable[OutputFile]) -> tuple[FileChange, ...]:
    """Compute new file contents without writing anything."""
    changes = []
    for output in outputs:
        path = root / output.path
        if path.is_symlink() and not path.exists():
            raise SyncError(f"{path}: dangling symlink; remove it or point it at a real file")
        existing = _read_raw(path)
        newline = "\r\n" if existing and "\r\n" in existing else "\n"
        normalized = existing.replace("\r\n", "\n") if existing is not None else None
        try:
            if output.managed:
                new = merge(normalized, output.content)
            else:
                new = own(normalized, output.content)
        except SyncError as exc:
            raise SyncError(f"{path}: {exc}") from exc
        content = new.replace("\n", newline)
        changes.append(FileChange(output.path, path, content, content != existing))
    return tuple(changes)


def _read_raw(path: Path) -> str | None:
    """Read without newline translation so CRLF files can be written back as CRLF."""
    if not path.exists():
        return None
    with path.open(encoding="utf-8", newline="") as handle:
        return handle.read()


def apply(changes: Iterable[FileChange]) -> tuple[Path, ...]:
    """Write changed files and return their paths."""
    written = []
    for change in changes:
        if not change.changed:
            continue
        _write_atomic(change.path, change.content)
        written.append(change.path)
    return tuple(written)


def _write_atomic(path: Path, content: str) -> None:
    """Replace ``path`` in one step, following symlinks and keeping the file mode."""
    target = path.resolve()
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = target.stat().st_mode & 0o777 if target.exists() else DEFAULT_FILE_MODE
    fd, tmp_name = tempfile.mkstemp(dir=target.parent, prefix=f".{target.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
            handle.write(content)
        os.chmod(tmp_name, mode)
        os.replace(tmp_name, target)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise
