"""Adapter interface for compiling rules into a tool's instruction file."""

from __future__ import annotations

from abc import ABC, abstractmethod

from praxis.rules import Rule, RuleSet, Section


def generated_notice(ruleset: RuleSet) -> str:
    """The HTML comment that opens every generated file."""
    source = f" from {ruleset.source.name}" if ruleset.source else ""
    return (
        f"<!-- Generated by praxis-agents{source}. Do not edit by hand: "
        "change the rules file and run `praxis sync`. -->"
    )


class Adapter(ABC):
    """Turns a rule set into the instruction file one AI coding tool reads.

    Subclasses set ``name`` (the ``--target`` value) and ``filename`` (the
    file written in the output directory), and implement ``render``.
    """

    name: str
    filename: str

    @abstractmethod
    def render(self, ruleset: RuleSet) -> str:
        """Return the full file contents for ``ruleset``."""


class MarkdownAdapter(Adapter):
    """Renders rules as Markdown that mirrors the source file's structure.

    Sections become headings (top-level sections at ``##``), rules become
    bullets, and rule details become nested bullets.
    """

    default_title: str = "Project rules"
    intro: str = ""

    def render(self, ruleset: RuleSet) -> str:
        blocks = [generated_notice(ruleset), f"# {ruleset.title or self.default_title}"]
        if self.intro:
            blocks.append(self.intro)
        blocks += _body(ruleset.description, ruleset.rules)
        for section in ruleset.sections:
            blocks += _section(section, depth=2)
        return "\n\n".join(blocks) + "\n"


def _section(section: Section, depth: int) -> list[str]:
    blocks = [f"{'#' * min(depth, 6)} {section.title}"]
    blocks += _body(section.description, section.rules)
    for child in section.sections:
        blocks += _section(child, depth + 1)
    return blocks


def _body(description: str, rules: list[Rule]) -> list[str]:
    blocks = [description] if description else []
    if rules:
        blocks.append("\n".join(_rule(rule) for rule in rules))
    return blocks


def _rule(rule: Rule) -> str:
    return "\n".join([f"- {rule.text}", *(f"  - {detail}" for detail in rule.details)])
