"""Adapter interface for compiling rules into a tool's instruction file."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Iterable, Protocol


class Rule(Protocol):
    """The parts of a parsed rule that adapters read."""

    title: str
    body: str


class RuleSet(Protocol):
    """The parts of a parsed rule set that adapters read."""

    @property
    def rules(self) -> Iterable[Rule]: ...


GENERATED_NOTICE = (
    "<!-- Generated by praxis-agents. Do not edit by hand: "
    "change your rules and run `praxis sync`. -->"
)


class Adapter(ABC):
    """Turns a rule set into the instruction file one AI coding tool reads.

    Subclasses set ``name`` (the ``--target`` value) and ``filename`` (the
    file written at the project root), and implement ``render``.
    """

    name: str
    filename: str

    @abstractmethod
    def render(self, ruleset: RuleSet) -> str:
        """Return the full file contents for ``ruleset``."""


class MarkdownAdapter(Adapter):
    """Renders rules as a Markdown document with one section per rule."""

    heading: str = "Project rules"
    intro: str = ""

    def render(self, ruleset: RuleSet) -> str:
        parts = [GENERATED_NOTICE, "", f"# {self.heading}", ""]
        if self.intro:
            parts += [self.intro, ""]
        for rule in ruleset.rules:
            parts.append(f"## {rule.title.strip()}")
            parts.append("")
            body = rule.body.strip()
            if body:
                parts += [body, ""]
        return "\n".join(parts).rstrip() + "\n"
