"""Write rendered output into files, and remove output praxis no longer generates.

Managed files: praxis touches only the block between its markers.
Owned text files: praxis writes the whole file and marks it with :data:`NOTICE`.
Owned byte files (skill scripts and assets): can't carry a notice, so praxis records their hashes in
a :data:`MANIFEST_NAME` file beside them and only replaces or deletes files that still match.
"""

from __future__ import annotations

import hashlib
import os
import tempfile
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path

from praxis_agents.model import BEGIN_MARKER as BEGIN
from praxis_agents.model import END_MARKER as END
from praxis_agents.model import NOTICE, OutputFile

DEFAULT_FILE_MODE = 0o644
# A file counts as praxis-generated only if NOTICE is a whole line near its top.
NOTICE_SEARCH_LINES = 20
NOTICE_SEARCH_BYTES = 8192
MANIFEST_NAME = ".praxis-manifest"
EXECUTABLE_BITS = 0o111
MAX_TRACKED_BYTES = 5_000_000  # largest skill script or asset; bigger files are never praxis's


class SyncError(ValueError):
    """Raised when an existing file can't be merged safely."""


@dataclass(frozen=True)
class FileChange:
    """The planned new content for one file, or its deletion."""

    relpath: str
    path: Path
    content: str | bytes
    changed: bool
    deleted: bool = False
    prune_until: Path | None = None  # after deleting, remove empty parents below this directory
    original: str | bytes | None = None  # content when planned (None: file didn't exist)
    guarded: bool = False  # recheck ``original`` before writing (deletions always recheck)
    executable: bool = False


def manifest_text(entries: Mapping[str, bytes]) -> str:
    """The manifest beside generated scripts and assets: NOTICE, then ``sha256  path`` lines."""
    lines = [f"{_sha256(data)}  {path}" for path, data in sorted(entries.items())]
    return "\n".join([NOTICE, *lines]) + "\n"


def parse_manifest(text: str) -> dict[str, str]:
    """``path -> sha256`` from a praxis-generated manifest; anything else counts as empty."""
    if not is_generated(text):  # a hand-written or copied manifest vouches for nothing
        return {}
    entries = {}
    for line in text.splitlines()[1:]:
        digest, separator, path = line.partition("  ")
        if separator and len(digest) == 64 and path:
            entries[path] = digest
    return entries


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def is_generated(text: str) -> bool:
    """True if ``text`` carries the praxis notice as a whole line near the top."""
    return any(line.strip() == NOTICE for line in text.splitlines()[:NOTICE_SEARCH_LINES])


def managed_block(content: str) -> str:
    body = content.strip()
    inner = f"{NOTICE}\n{body}\n" if body else f"{NOTICE}\n"
    return f"{BEGIN}\n{inner}{END}"


def merge(existing: str | None, content: str) -> str:
    """Return ``existing`` with its managed block replaced (or appended) by ``content``."""
    block = managed_block(content)
    if existing is None or not existing.strip():
        return block + "\n"

    span = _block_span(existing)
    if span is None:
        return existing.rstrip("\n") + "\n\n" + block + "\n"
    start, stop = span
    return existing[:start] + block + existing[stop:]


def unmerge(existing: str) -> str | None:
    """Return ``existing`` without its managed block, or ``None`` if nothing else remains."""
    span = _block_span(existing)
    if span is None:
        return existing
    start, stop = span
    parts = (existing[:start].rstrip("\n"), existing[stop:].lstrip("\n"))
    remaining = "\n\n".join(part for part in parts if part)
    return remaining.rstrip("\n") + "\n" if remaining.strip() else None


def _block_span(existing: str) -> tuple[int, int] | None:
    begins, ends = existing.count(BEGIN), existing.count(END)
    if begins == 0 and ends == 0:
        return None
    if begins != 1 or ends != 1 or existing.index(BEGIN) > existing.index(END):
        raise SyncError(f"malformed praxis markers; expected one {BEGIN} followed by one {END}")
    return existing.index(BEGIN), existing.index(END) + len(END)


def own(existing: str | None, content: str) -> str:
    """Return ``content`` for an owned file; refuse to replace a file praxis didn't write."""
    if existing is not None and not is_generated(existing):
        raise SyncError("file exists and was not generated by praxis; move or delete it first")
    return content


def plan(root: Path, outputs: Iterable[OutputFile]) -> tuple[FileChange, ...]:
    """Compute new file contents without writing anything."""
    changes = []
    for output in outputs:
        path = root / output.path
        if path.is_symlink() and not path.exists():
            raise SyncError(f"{path}: dangling symlink; remove it or point it at a real file")
        if not output.managed and not _inside(root, path):
            raise SyncError(
                f"{path}: resolves outside the project through a symlink; refusing to write there"
            )
        if isinstance(output.content, bytes):
            changes.append(_plan_bytes(root, output, path))
            continue
        existing = _read_raw(path)
        newline = "\r\n" if existing and "\r\n" in existing else "\n"
        normalized = existing.replace("\r\n", "\n") if existing is not None else None
        try:
            if output.managed:
                new = merge(normalized, output.content)
            else:
                new = own(normalized, output.content)
        except SyncError as exc:
            raise SyncError(f"{path}: {exc}") from exc
        content = new.replace("\n", newline)
        changes.append(FileChange(output.path, path, content, content != existing))
    return tuple(changes)


def _inside(root: Path, path: Path) -> bool:
    return path.resolve().is_relative_to(root.resolve())


def _plan_bytes(root: Path, output: OutputFile, path: Path) -> FileChange:
    """Plan a script or asset; replace an existing file only if praxis wrote it, unedited."""
    existing = None
    if path.exists():
        if path.stat().st_size > MAX_TRACKED_BYTES:
            raise SyncError(
                f"{path}: file exists and was not generated by praxis; move or delete it first"
            )
        existing = path.read_bytes()
    if existing is not None and existing != output.content:
        recorded = _recorded_hash(root, path)
        if recorded is None:
            raise SyncError(
                f"{path}: file exists and was not generated by praxis; move or delete it first"
            )
        if _sha256(existing) != recorded:
            raise SyncError(
                f"{path}: file was edited since praxis generated it; move or delete it first"
            )
    is_executable = existing is not None and bool(path.stat().st_mode & EXECUTABLE_BITS)
    mode_differs = existing is not None and is_executable != output.executable
    changed = existing != output.content or mode_differs
    return FileChange(
        output.path,
        path,
        output.content,
        changed,
        original=existing,
        guarded=True,
        executable=output.executable,
    )


def _recorded_hash(root: Path, path: Path) -> str | None:
    """The hash the nearest manifest above ``path`` records for it, if any."""
    for directory in path.parents:
        if directory != root and root not in directory.parents:
            return None
        manifest = directory / MANIFEST_NAME
        if manifest.is_file() and not manifest.is_symlink():
            entries = parse_manifest(manifest.read_text(encoding="utf-8", errors="replace"))
            return entries.get(path.relative_to(directory).as_posix())
    return None


def plan_stale(
    root: Path,
    outputs: Iterable[OutputFile],
    owned_dirs: Iterable[str],
    managed_paths: Iterable[str],
) -> tuple[FileChange, ...]:
    """Plan removal of praxis output that ``outputs`` no longer includes.

    Owned files (marked with :data:`NOTICE`) under ``owned_dirs`` are deleted; managed blocks in
    ``managed_paths`` are removed, deleting the file if nothing else is left in it.
    """
    produced = {os.path.normpath(output.path) for output in outputs}
    produced_ids = _file_ids(root / relpath for relpath in produced)
    changes = [
        change
        for owned in owned_dirs
        for change in _stale_owned_files(root, root / owned, produced, produced_ids)
    ]
    for relpath in managed_paths:
        if relpath not in produced:
            change = _stale_managed_block(root / relpath, relpath)
            if change is not None:
                changes.append(change)
    return tuple(changes)


def _file_ids(paths: Iterable[Path]) -> set[tuple[int, int]]:
    """Device and inode of each existing path, to match files across spellings (e.g. case)."""
    ids = set()
    for path in paths:
        try:
            stat = path.stat()
        except OSError:
            continue
        ids.add((stat.st_dev, stat.st_ino))
    return ids


def _stale_owned_files(
    root: Path, base: Path, produced: set[str], produced_ids: set[tuple[int, int]]
) -> list[FileChange]:
    # Never clean up through a symlink that leads out of the project (e.g. to ~/.claude/skills).
    if not base.is_dir() or not base.resolve().is_relative_to(root.resolve()):
        return []
    stale: dict[str, FileChange] = {}

    def consider(path: Path, original: str | bytes | None) -> None:
        relpath = path.relative_to(root).as_posix()
        if original is None or relpath in produced or _file_ids([path]) & produced_ids:
            return
        stale[relpath] = FileChange(
            relpath, path, "", True, deleted=True, prune_until=base, original=original
        )

    # os.walk doesn't follow symlinked subdirectories, so nothing outside ``base`` is considered.
    for directory, _, names in os.walk(base):
        for name in names:
            path = Path(directory) / name
            if path.is_symlink():
                continue
            consider(path, _read_generated(path))
            if name == MANIFEST_NAME:
                for listed, original in _unedited_manifest_files(base, path):
                    consider(listed, original)
    # Delete listed files before their manifest, so a crash midway never orphans them.
    return sorted(
        stale.values(), key=lambda change: (change.path.name == MANIFEST_NAME, change.relpath)
    )


def _unedited_manifest_files(base: Path, manifest: Path) -> list[tuple[Path, bytes]]:
    """Files a manifest lists that still match their recorded hash (edited ones are left alone)."""
    try:
        entries = parse_manifest(manifest.read_text(encoding="utf-8", errors="replace"))
    except OSError:
        return []
    unedited = []
    for relpath, digest in entries.items():
        path = manifest.parent / relpath
        # A manifest is data: ignore entries that would reach outside the skills directory.
        if ".." in Path(relpath).parts or Path(relpath).is_absolute():
            continue
        if path.is_symlink() or not path.is_file():
            continue
        if not path.resolve().is_relative_to(base.resolve()):
            continue
        if path.stat().st_size > MAX_TRACKED_BYTES:
            continue
        data = path.read_bytes()
        if _sha256(data) == digest:
            unedited.append((path, data))
    return unedited


def _read_generated(path: Path) -> str | None:
    """Return the file's text if praxis generated it; ``None`` for anything else or unreadable."""
    try:
        with path.open("rb") as handle:
            prefix = handle.read(NOTICE_SEARCH_BYTES).decode("utf-8", errors="replace")
        if not is_generated(prefix):
            return None
        return _read_raw(path)
    except (OSError, UnicodeDecodeError):
        return None


def _stale_managed_block(path: Path, relpath: str) -> FileChange | None:
    # A symlinked managed file (e.g. CLAUDE.md -> AGENTS.md) belongs to its target; leave it.
    if path.is_symlink():
        return None
    existing = _read_raw(path)
    if existing is None:
        return None
    newline = "\r\n" if "\r\n" in existing else "\n"
    try:
        remaining = unmerge(existing.replace("\r\n", "\n"))
    except SyncError as exc:
        raise SyncError(f"{path}: {exc}") from exc
    if remaining is None:
        return FileChange(relpath, path, "", True, deleted=True, original=existing)
    content = remaining.replace("\n", newline)
    return FileChange(relpath, path, content, True) if content != existing else None


def _read_raw(path: Path) -> str | None:
    """Read without newline translation so CRLF files can be written back as CRLF."""
    if not path.exists():
        return None
    with path.open(encoding="utf-8", newline="") as handle:
        return handle.read()


def apply(changes: Iterable[FileChange]) -> tuple[Path, ...]:
    """Write or delete changed files and return their paths."""
    touched = []
    for change in changes:
        if not change.changed:
            continue
        if change.deleted:
            if isinstance(change.original, bytes):
                current = change.path.read_bytes() if change.path.exists() else None
            else:
                current = _read_raw(change.path)
            if current is None:  # already gone
                continue
            if current != change.original:
                raise SyncError(
                    f"{change.path}: changed since it was planned for deletion; rerun sync"
                )
            change.path.unlink()
            _prune_empty_dirs(change.path.parent, change.prune_until)
        else:
            if change.guarded:
                current = change.path.read_bytes() if change.path.exists() else None
                if current != change.original:
                    raise SyncError(f"{change.path}: changed since it was planned; rerun sync")
            _write_atomic(change.path, change.content, executable=change.executable)
        touched.append(change.path)
    return tuple(touched)


def _prune_empty_dirs(directory: Path, stop: Path | None) -> None:
    """Remove empty directories from ``directory`` up to, but not including, ``stop``."""
    if stop is None:
        return
    while directory != stop and stop in directory.parents:
        try:
            directory.rmdir()
        except OSError:  # not empty
            return
        directory = directory.parent


def _write_atomic(path: Path, content: str | bytes, executable: bool = False) -> None:
    """Replace ``path`` in one step, following symlinks and keeping the file mode."""
    target = path.resolve()
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = target.stat().st_mode & 0o777 if target.exists() else DEFAULT_FILE_MODE
    if isinstance(content, bytes):  # scripts follow their shebang; text files keep their mode
        mode = mode | EXECUTABLE_BITS if executable else mode & ~EXECUTABLE_BITS
    fd, tmp_name = tempfile.mkstemp(dir=target.parent, prefix=f".{target.name}.", suffix=".tmp")
    try:
        if isinstance(content, bytes):
            with os.fdopen(fd, "wb") as handle:
                handle.write(content)
        else:
            with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
                handle.write(content)
        os.chmod(tmp_name, mode)
        os.replace(tmp_name, target)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise
